### PR TITLE
some docker fixes

### PR DESCRIPTION
**Pull request by rcemper**
- actual image 
- check-caps false
- ISCAgent fals e for faster start

### CODE REVIEW

**Comment by grongierisc** [comment]
Thanks Robert

**Comment by rcemper** [comment]
you closed the PR,
but DOCKERFILE and docker-compose.yaml are still broken and Docker install fails !

that wasn't the purpose of the PR.

**Comment by grongierisc** [comment]
I'm rewriting the demo to make it works, i will let you know as soon as it's finish, i'm sorry to publish unfinished work on OpenExange but I have been pushed hard to do so ;)

**Comment by grongierisc** [comment]
https://github.com/grongierisc/JsonTraceViewer/commit/2d038af3b935a79bcf25b55105a6a5a0c0bf1123

**Pull request closed without merging**
